### ISSUE TITLE
H1 issue

### ISSUE THREAD

**Issue by lexyfh** [lexyfh/modularity-mindfulness#1]
I can't figure out how to make the h1 look like the screenshots, not sure if I set up my html wrong

@wendywarren
@KarenMendozaGarza

**Comment by wendywarren** [comment]
Hi @lexyfh,

You're on the right track with your H1. The html here is correct.

`<h1><i lang="ja">枯山水</i> <span>Rock Gardens</span></h1>`

Consider what happens when you apply `display: flex;` to an element.

Right now both the Japanese characters and Rock Gardens appear beside each other. Even though you've applied `display: flex;` to the `<header>` you can still apply it to the flex items within. So nesting one flex inside another.

If we apply `display: flex;` to the `<h1>` we can set the direction we'd like our content to go using `flex-direction` and we can also align them if necessary using `align-items`.

I hope that helps. :)

Wendy
